### ISSUE TITLE
Install failure

### ISSUE THREAD

**Issue by riveraj33** [dgreif/ring-alarm#14]
Hello. I’ve used this plugin for a few months and unfortunately I had to reinstall raspian on my pi and start over with a bunch of things. Homebridge and this plug in are one of those. I’m getting an error when trying to install this plug in. I have the latest version on homebridge. I get a command failed and permission denied. I’ll try to post a pic tomorrow. I can’t forgive out how to paste a photo from my iPhone to this thread.

**Comment by dgreif** [comment]
@riveraj33 sorry to hear you are having issues.  Seems like quite a few people have had similar issues with npm installs lately.  Check through some of the other issues on this repo to see if any help you get past the permissions issue.  Let me know how it goes.

**Comment by riveraj33** [comment]
Ok here is an imgur link 

https://imgur.com/a/bPEx2Y6

**Comment by dgreif** [comment]
@riveraj33 looks like it is doing something odd with the api dependency, which is a github url instead of pulling from npm.  I'm working on merging the homebridge and api repos into one, which should hopefully fix the issue.  I'll post back when i'm done, but it will probably be a while since I don't have much free time right now.  I was able to install `homebridge-ring-alarm` on a clean docker image this morning so I know it can be installed as-is.  Hopefully you can find a solution for your setup until I get the repos moved around.

**Comment by dgreif** [comment]
@riveraj33 can you try installing `v1.2.2`? I pulled my `ring-alarm` api into this repo so that I don't have as many external dependencies.

**Comment by riveraj33** [comment]
I actually ended up deleting homebridge and reinstalling it. That seemed to clear it up. Mine still shows as 1.2. I’d hate to update it and then break it again lol
