### ISSUE TITLE
Add support for police/fire panic button

### ISSUE THREAD

**Issue by tjohns** [dgreif/ring-alarm#30]
Ring Alarm recently added a panic button to their mobile app, which can either (a) trigger the siren on the base station, (b) request a police response, or (c) request a fire department response. (Options (b)/(c) require an active monitoring plan.)

It would be interesting to expose an API endpoint for this feature, since it would be very useful for writing certain types of automation rules.

(On the other hand, one would have to be very careful with this API to avoid false alarms. Testing could also be a challenge.)

**Comment by codahq** [comment]
@dgreif Here's how to sound and silence the siren.  

["message",{"body":[{"zid":"${panel_zid}","command":{"v1":[{"commandType":"security-panel.${mode}","data":{}}]}}],"datatype":"DeviceInfoSetType","dst": "${dst_zid}","msg":"DeviceInfoSet","seq":${seq}}]

${mode} can be "sound-siren" or "silence-siren"

I'm not going to tell you how to notify the police or fire department.  I feel like that could be abused or accidentally misunderstood and there's no reason to automate it anyway.  (The above message flashes the lights on the base as well.  From the API layer there is no way to separate the lights from the siren.  I wished there was.)

**Comment by dgreif** [comment]
Thanks for the info! I just received the new button in my app yesterday.  I'll take a look at adding it when I get a chance.

**Comment by tjohns** [comment]
The big use case I can see for adding the police/fire modes would be for integrating unsupported third-party sensors via Home Assistant, or building a fire alarm pull station (since the official Ring keypad doesn't have a manual fire alarm button).

But I also agree that exposing those is something best approached with caution.

**Comment by codahq** [comment]
They have a first party solution for this, no?  What does their panic button do?  I assumed that would dispatch police or fire or at least get that started.

**Comment by tjohns** [comment]
@codahq They do have a Z-Wave panic button, but it's police only, afaik. Same as the panic mode on the keypad.

They don't have any way to trigger a manual fire alarm, other than the new soft button in the app.

**Comment by dgreif** [comment]
I added the siren logic directly to each location (`location.soundSiren()`, `location.silenceSiren()`).  I also added a switch to the homebridge plugin for this, called `Ring Alarm Siren`.  As for police/fire, I made it easy to call those programmatically with `location.sendCommandToSecurityPanel('secuirty-panel.unknown-command-here')`.  I think this is a good enough sanity check to make sure anyone implementing these commands understands the gravity of what they are doing.  @codahq would you be kind enough to supply the commands for policy/fire?  Specifically the `commandType` and `data` fields you see being used in those calls.

**Comment by codahq** [comment]
Unfortunately, no.  I'm going to pass on providing any information on the fire/police commands.  Somebody else can do that.  Even though there is nothing illegal against reverse engineering by itself it's probably against the terms of use to call their private APIs directly because of liability and/or other reasons.  If somebody were to call the police or fire repeatedly using this library (or my work) and get in trouble or if somebody "depended" on this solution and it didn't work for example there would be the possibility of legal ramifications.  

I don't want to put myself in a situation where I might have to defend myself legally.  Up to this point everything I've supplied (and done personally in my own library because I don't actually use yours) avoids liability against/for others.  At least that is how I see it.  I'm going to keep my contributions here the same.  

This project is a little different than just turning lights off/on because of the security aspect.

**Comment by dgreif** [comment]
@codahq I totally understand! I agree with your logic, and really appreciate all of the help you have provided so far.  I'll leave my `sendCommandToSecurityPanel` method in place as I am using it internally for siren and alarm mode changes.   Can't stop others from using it if they figure out the commands and use them at their own risk.
