### ISSUE TITLE
Keypad & Cameras not showing up

### ISSUE THREAD

**Issue by Jborn4christ** [dgreif/ring-alarm#33]
I am pretty experienced with running Homebridge, installed RingAlarm. Home picked up the motion sensor on my ring doorbell and floodlight, but no other devices showed up. No cameras, and no keypad control. Am I completely missing something? Is there additional configurations I need to apply?

 "platforms": [
    {
      "platform": "RingAlarm",
      "email": "myemail@gmail.com",
      "password": "mypassword",
      "locationIds": [],
      "alarmOnEntryDelay": false,
      "beamDurationSeconds": 60,
      "hideLightGroups": false
    },

**Comment by Jborn4christ** [comment]
I figured it out. Had to remove the line from config about locations. I had just left it blank thinking it would bypass.

**Comment by dgreif** [comment]
@Jborn4christ thanks for letting me know what the issue was! I was questioning whether or not I had messed something up in the v3.0.0 release.  I think a number of people have been confused by the optional parameters, so I pushed up some changes to the readme to hopefully clarify.  You do not need _any_ of the optional parameters unless you actually want to change from the default behavior.  All you have to have is platform, email and password.  Sorry for the confusion!
