### ISSUE TITLE
Support for fire alarms and such?

### ISSUE THREAD

**Issue by ajcutshall** [dgreif/ring-alarm#9]
Hey there! Love this homebridge integration, it’s made my ring alarm much more useful with automation! Anyways, I just got one of those Z-Wave fire alarms from First Alert and it ties into my ring alarm. Do you have any plans to add in support for them, or have any idea how easy it might be to do so? Would be awesome to be able to turn on all the lights and turn off the HVAC in the event of an alarm. Thanks for making and sharing this awesome plugin! Your hard work is much appreciated!

**Comment by dgreif** [comment]
@ajcutshall glad to hear the plugin is working well for you! I've been watching Ring's releases at CES closely and figured there would be some request rolling in for new device types 😂.  I've taken an initial stab at smoke/co devices as well as the smoke/co listener.  Give `v1.2.0` a try and let me know how it works.  Since I don't have one to try, I could be completely off, but it appears that Ring exposes the smoke and co as two separate devices.  Let me know if the devices show up in HomeKit, and give the smoke alarm a try (might have to actually set it off with some smoke, not sure if hitting the test button will activate it in Ring).  Looking forward to your results 😄

**Comment by ajcutshall** [comment]
Hey @dgreif, sorry for the delay in getting back to you! I just updated and can confirm that the CO and Smoke alarm shows up in homebridge. It shows up in the same way that it does in the ring app, as two separate devices. I’ll see if I can get the fire alarm to trigger without summoning the fire department (I’ve got monitoring) and will report back with findings on how automations work. Thanks again!!

**Comment by jamesg311** [comment]
I just came hear to add that the suggestion for an automation when the Ring Alarm goes off was a great one, thank you. I set a lot of the lights inside/outside of my house to turn on automatically when the Alarm goes off.

Thanks as well for @dgreif for your hard work here! Let me know if you accept PayPal or anything like that so I can buy you a coffee or something for your work.

**Comment by dgreif** [comment]
@ajcutshall thanks for verifying that the device shows up correctly.  I was a little confused when the ring app source code appeared to split the CO and smoke into separate devices, so it's good to know that's how it actually shows up in the app.  I think there is a test page somewhere in the app for testing your smoke alarms but I'm not sure exactly where it is (again, looking at minified source code isn't an exact science 😄).  If you can find the test page give that a try, otherwise I think a "real" event is going to be necessary to test it.

**Comment by jamesg311** [comment]
Ah, I looked and didn't find it but checked my PayPal receipts and I think I sent you some cash back in December. Thanks again for your work!

**Comment by dgreif** [comment]
@ajcutshall did you get a chance to test this out with a "real" fire event?

**Comment by dgreif** [comment]
I'm going to assume this is good to go.  @ajcutshall let me know if you test it out and run into any issues.

**Comment by ajcutshall** [comment]
Hey @dgreif, sorry for not getting back to you for such a long time. I’ve been busy with a bunch of life stuff. As it turns out, E-Cigs will set the fire alarm off. When the alarm went off, HomeKit notified me as expected and also turned on every light, as I have configured! I just hope the fire department isn’t too peeved.

**Comment by dgreif** [comment]
@ajcutshall thanks for letting me know, really glad to hear it worked!

**Comment by malmentm** [comment]
@ajcutshall which smoke sensor did you use?
